// <auto-generated />
using System;
using GestionFetes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionFetes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GestionFetes.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GestionFetes.Models.Fete", b =>
                {
                    b.Property<int>("IdFete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateFete")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSalle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NbInvitesMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdFete");

                    b.HasIndex("IdSalle");

                    b.ToTable("Fetes");

                    b.HasData(
                        new
                        {
                            IdFete = 1,
                            DateFete = new DateTime(2026, 5, 20, 9, 22, 43, 646, DateTimeKind.Local).AddTicks(2838),
                            Description = "Anniversaire de Mohamed - 30 ans",
                            Duree = 5,
                            IdSalle = 1,
                            NbInvitesMax = 80,
                            Type = "Anniversaire"
                        },
                        new
                        {
                            IdFete = 2,
                            DateFete = new DateTime(2026, 6, 4, 9, 22, 43, 646, DateTimeKind.Local).AddTicks(2857),
                            Description = "Mariage de Sonia et Karim",
                            Duree = 8,
                            IdSalle = 2,
                            NbInvitesMax = 300,
                            Type = "Mariage"
                        },
                        new
                        {
                            IdFete = 3,
                            DateFete = new DateTime(2026, 5, 12, 9, 22, 43, 646, DateTimeKind.Local).AddTicks(2859),
                            Description = "Fête de fin d'année d'entreprise",
                            Duree = 4,
                            IdSalle = 3,
                            NbInvitesMax = 60,
                            Type = "Autre"
                        });
                });

            modelBuilder.Entity("GestionFetes.Models.Invitation", b =>
                {
                    b.Property<int>("IdInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConfirmeInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DateConfirmation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInvitation")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInvite")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdInvitation");

                    b.HasIndex("IdInvite");

                    b.HasIndex("IdFete", "IdInvite")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("GestionFetes.Models.Invite", b =>
                {
                    b.Property<int>("IdInvite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseInvite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdInvite");

                    b.ToTable("Invites");

                    b.HasData(
                        new
                        {
                            IdInvite = 1,
                            AdresseInvite = "Tunis Centre",
                            DateNaissance = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@email.com",
                            Nom = "Ben Ali",
                            Prenom = "Ahmed",
                            Telephone = "22345678"
                        },
                        new
                        {
                            IdInvite = 2,
                            AdresseInvite = "La Marsa, Tunis",
                            DateNaissance = new DateTime(1985, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatma@email.com",
                            Nom = "Trabelsi",
                            Prenom = "Fatma",
                            Telephone = "55123456"
                        },
                        new
                        {
                            IdInvite = 3,
                            AdresseInvite = "Ariana, Tunis",
                            DateNaissance = new DateTime(1995, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef@email.com",
                            Nom = "Khelil",
                            Prenom = "Youssef",
                            Telephone = "98765432"
                        });
                });

            modelBuilder.Entity("GestionFetes.Models.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddresseSalle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("PrixParHeure")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSalle");

                    b.HasIndex("NomSalle")
                        .IsUnique();

                    b.ToTable("Salles");

                    b.HasData(
                        new
                        {
                            IdSalle = 1,
                            AddresseSalle = "12 Rue de la Paix, Tunis",
                            Capacite = 200,
                            NomSalle = "Salle Crystal",
                            PrixParHeure = 150.0
                        },
                        new
                        {
                            IdSalle = 2,
                            AddresseSalle = "45 Avenue Habib Bourguiba, Sfax",
                            Capacite = 500,
                            NomSalle = "Palais des Roses",
                            PrixParHeure = 300.0
                        },
                        new
                        {
                            IdSalle = 3,
                            AddresseSalle = "8 Rue des Oliviers, Sousse",
                            Capacite = 100,
                            NomSalle = "Villa Jasmin",
                            PrixParHeure = 100.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GestionFetes.Models.Fete", b =>
                {
                    b.HasOne("GestionFetes.Models.Salle", "Salle")
                        .WithMany("Fetes")
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GestionFetes.Models.Invitation", b =>
                {
                    b.HasOne("GestionFetes.Models.Fete", "Fete")
                        .WithMany("Invitations")
                        .HasForeignKey("IdFete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFetes.Models.Invite", "Invite")
                        .WithMany("Invitations")
                        .HasForeignKey("IdInvite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fete");

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GestionFetes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GestionFetes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFetes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GestionFetes.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionFetes.Models.Fete", b =>
                {
                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("GestionFetes.Models.Invite", b =>
                {
                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("GestionFetes.Models.Salle", b =>
                {
                    b.Navigation("Fetes");
                });
#pragma warning restore 612, 618
        }
    }
}
